### ISSUE TITLE
mqtt values not under topic

### ISSUE THREAD

**Issue by robwolff3** [birdie1/victron#15]
I just just got this project setup, thanks for making it by the way! Once it was connected to my smart solar 100/30 via vedirect and to my mqtt broker I noticed values being posted on the base of the mqtt broker and not under the topic I set. Is it suppose to do that? Seems like it would conflict when I add a smart shunt and it tries to post to the same base of the mqtt server and not its own sub-topic.

![This is an image](https://i.imgur.com/W7QiU9Q.png)

P.S. Do you see any problem with setting time timer to 1 second repeat on serial? For more real time values.

P.P.S. I had to downgrade from newer version of python down to python 3.8.13 to get the project to work. Others might find that useful in the readme.

**Comment by robwolff3** [comment]
Also noticed values did not properly populate in home assistant with `hass: True`


![This is an image](https://i.imgur.com/649WG8f.png)

**Comment by birdie1** [comment]
Yes, this seems wrong. Looks like it publishes all the meta stuff like serial correctly and only the electrical values are posted on the base. I think I found the issue, please try the newest commit: https://github.com/birdie1/victron/commit/4efa6f83463f2618c1a8be209f8fcde37d814512

I think the reading of the values is taking longer than 1 second to read, so I am not sure what will happen. If you try it out, would be nice if you tell us the result.

I am running 3.10.4 on my local computer and 3.9.2 on my raspberry pi and both are working. Which version did you try? What was the error?

**Comment by robwolff3** [comment]
Oh one last question, sorry :)

I am using this as the entry command in the docker container `python3 victron.py -d 0`, is there or could there be a way added in the future to not have to specify a device and it check all devices defined in the configuration file? That could make the container more universal for however many devices people have defined with it.

**Comment by birdie1** [comment]
> That fixed it! Everything is working perfect now.
> 
> As for the python version, I am building your project in a docker container. It works great when I use the base image `python:3.8.13-slim-bullseye` but when I used the base image `python:3.10.4-slim-bullseye` I get this error during container building: https://pastebin.com/VzJY91Yf

I will check the errors, looks like it cannot build some of the modules. I think I should clean up the requirements file.

> On the reading time. I don't know your project or python so I'm not an expert :) . But would a push type system work better then polling? Keeping the connection over serial open and publishing to mqtt every time a value is updated? I do realize this probably wont work for bluetooth, but maybe serial?

That sounds reasonable. Actually the mqtt connection is kept open, but I think the serial connection is currently closed every time after getting values. I will add this to the code

> I am using this as the entry command in the docker container python3 victron.py -d 0, is there or could there be a way added in the future to not have to specify a device and it check all devices defined in the configuration file? That could make the container more universal for however many devices people have defined with it.

I removed this from the code a few months ago, as it was making trouble with bluetooth. I could add it if only one device exists in config. Would it be helpful for you, or do you have multiple devices specified?

**Comment by robwolff3** [comment]
Re: Specifying a device. No worries. It would just allow running the container more generically and dynamically. Like only having to run one container and it dynamically picking up the number of devices from the config, because the execution command his hard coded in the DockerFile. However currently one could just instantiate the container multiple times with separate configs. That seem to more align with how you have designed things.
