### ISSUE TITLE
[FR] Add expire_after option for hass sensors

### ISSUE THREAD

**Issue by robwolff3** [birdie1/victron#22]
Sometimes my smartshunt connected by usb disconnects and values remain static in homeassistant. It would be nice to have a expire_after option so its very obvious the values are old and not updating.

https://www.home-assistant.io/integrations/sensor.mqtt/#expire_after

**Comment by birdie1** [comment]
Yeah, that sounds reasonable. I was not aware this option exists in hass. I will add it.

**Comment by birdie1** [comment]
I have added expire_after option to "Latest" and "Battery" sensors. Commit https://github.com/birdie1/victron/commit/e59630cd705235ec1f69527464cb78a52cab26e9
