### ISSUE TITLE
Cannot execute script

### ISSUE THREAD

**Issue by Naaf3** [birdie1/victron#23]
Hi Jonas,

I installed your script on my Raspberry Pi 3 B+ and connected the Victron SmartSolar 100 30 via original USB-Cable to the Pi.

I can check the Version of the script and so on, but I cannot execute the script properly. When I try, I get this:
pi@rpi:~/victron$ ./victron.py -d SmartsolarAlfred
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/home/pi/victron/./victron.py", line 24, in victron_thread
    v = Victron(config, vdevice_config, output, args, thread_count, thread_q)
  File "/home/pi/victron/lib/victron.py", line 28, in __init__
    self.victron_type = VictronSerial(device_config, self.output)
  File "/home/pi/victron/lib/victron_serial/victron_serial.py", line 20, in __init__
    from lib.victron_serial.victron_smartsolar import Smartsolar
  File "/home/pi/victron/lib/victron_serial/victron_smartsolar.py", line 4, in <module>
    from vedirect import Vedirect
ImportError: cannot import name 'Vedirect' from 'vedirect' (unknown location)

Do you have any idea what causes this problem?

Regards
Sebastian

**Comment by birdie1** [comment]
Hello Sebastian,
looks like you missed to install https://github.com/karioja/vedirect. The serial communication depends on this library.

Regards
Jonas

**Comment by Naaf3** [comment]
Got it installed. Worked with the Raspbian OS 32bit image.

**Comment by Naaf3** [comment]
Sorry, but I have to reopen the issue, because the problem still exists.

As you said, I installed the vedirect, but it is still not working. Do I have to put it somewhere special?

**Comment by Naaf3** [comment]
Now I've got it running. I only downloaded the vedirect stuff, but missed to install it. Now it's working :-)
